spring:
  datasource:
    url: jdbc:mysql://123.60.40.72:3306/vocaloid_game?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=3&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 987b96aed3e0aa91fb4961e2e00301b3b44feef265605e2dfe4ac86560cf9765
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 10001

# 文件上传配置
spring.servlet.multipart:
  max-file-size: 5MB
  max-request-size: 5MB
